### ISSUE TITLE
【资源】素材库

### ISSUE THREAD

**Issue by hanlin0516** [HanLin0516/Writer-Business-Plan#3]
BP协作地址：https://www.icloud.com/keynote/0nhVdJqaZF4GwMrpGr_j3dasA#%E7%BA%A2%E8%89%B2
密码：BP

另外：
各种资料、论文，亲朋采访、问卷，图片、音乐，想法、启发……尽量往这里扔。

**Comment by hanlin0516** [comment]
- 组长从隔壁搬运，整理得比我好TAT[https://github.com/13space/LittlePrinceInNutShell/issues/1]
  *[如何高效完成结业项目？](https://github.com/OpenMindClub/Writer003/issues/215#issuecomment-244585597)

**Comment by rusell123** [comment]
- 平面化动画展示——[北京房事](http://v.youku.com/v_show/id_XMjY4MTk2MDYw.html?spm=0.0.collectVideo.5~5!330~5~5~A.7BWrll)
- 免费图片素材网站[librestock](http://librestock.com/)
- keynote经典演示视频[Ducati Superbike](http://v.youku.com/v_show/id_XMzU4OTE2MzA0.html?beta&from=s1.8-1-1.2&spm=0.0.0.0.Mr8uM9)——keynote文件下载(密码: jtqy)[Ducati 街车](https://pan.baidu.com/s/1bp1Id0V)
- [App 产品原型设计用什么软件](https://www.zhihu.com/question/20403141)
- [BP背景音乐](http://music.163.com/#/playlist?id=465759042)——推荐Experience、Equality 7-2521

**Comment by hanlin0516** [comment]
- 配色资源 https://github.com/OpenMindClub/Writer003/wiki/SuggestionSlideColorDesign 
- [keynote帮助](https://help.apple.com/keynote/mac/6.5/#/tan79a8f6388)
- 扁平icon 
  - [千图](http://www.58pic.com/tupian/bianpinghuatubiao.html）
  - [uisdc](http://www.uisdc.com/flat-vector-icons-for-designers)
  - [iconfront](http://www.iconfont.cn/)
- [知乎](https://www.zhihu.com/question/21274267)
