### ISSUE TITLE
【BP】Q&A汇总

### ISSUE THREAD

**Issue by hanlin0516** [HanLin0516/Writer-Business-Plan#4]
Q：
A：

7w3d 前，需要把问题汇总到issue下。

7w6d前，基本回答完毕。解答尽量简明，常规问题希望能用两三条微博的长度回答完。微信上有前期讨论。以及5d20：00，大家zoom在线。

**Comment by kirolan** [comment]
# 客户群

针对哪批客户群，从项目的优势上来说，更适合年轻人。但去医院多的都是老年人。

# 费用

自己验血的费用和医院的相比贵多少？那些老年人更看重费用，而不是时间

# 操作

操作难易程度如何？涉及哪些环节？

# 安全
- 血液无污染

如何保障自采的血样复合检验要求？途中被污染的几率多大？
- 个人信息安全

如何防止不法分子利用这些信息？

# 宣传

如何让消费者愿意尝试这种新方法？没有值得信赖的渠道，人们更愿意选择正规医院。

**Comment by hanlin0516** [comment]
- 你们和Therano有什么不同？

**Comment by rusell123** [comment]
-  如何吸引中老年——初期与各大医院及权威科研机构建立业务关系，借用其实验室资源验血，也是线下推广。
-  如何吸引青年——与丁香园等线上医疗网站建立业务联系，开发优质app，充分互联网优势。
-  Theranos主打针刺验血的技术优势，我们项目主要优势是简单快捷的验血流程。
